spring:
    application: 
        name: item-service 
server: 
   port: 8001

eureka: 
    client: 
       service-url: 
            defaultZone: http://eureka1:2001/eureka
rabbitmq:
    host: 192.168.230.130
    port: 5672
    username: admin
    password: admin
            